from __future__ import annotations

import csv
import hashlib
import importlib.util
import json
import os
import platform
import re
import socket
import sys
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Sequence

import numpy as np
import tensorflow as tf


# ============================================================
# PATHS
# ============================================================

THIS_FILE = Path(__file__).resolve()

EXPERIMENT_DIR = THIS_FILE.parent
EXPERIMENTS_ROOT = EXPERIMENT_DIR.parent
NEW_ROOT = EXPERIMENTS_ROOT.parent

BASELINE_PROTOCOL_PATH = (
    EXPERIMENTS_ROOT
    / "03_baseline_comparison"
    / "00_common_protocol.py"
)


# ============================================================
# LOAD VALIDATED BASELINE PROTOCOL
# ============================================================

if not BASELINE_PROTOCOL_PATH.exists():

    raise FileNotFoundError(
        "Validated baseline protocol was not found:\n"
        f"{BASELINE_PROTOCOL_PATH}"
    )


spec = importlib.util.spec_from_file_location(
    "validated_baseline_protocol",
    BASELINE_PROTOCOL_PATH,
)

if spec is None or spec.loader is None:

    raise ImportError(
        "Unable to load validated baseline protocol:\n"
        f"{BASELINE_PROTOCOL_PATH}"
    )


baseline = importlib.util.module_from_spec(
    spec
)

spec.loader.exec_module(
    baseline
)


# ============================================================
# AUTHORITATIVE PROJECT PATHS
# ============================================================

ORIGINAL_ROOT = baseline.ORIGINAL_ROOT
NEW_ROOT = baseline.NEW_ROOT
DATA_ROOT = baseline.DATA_ROOT
SEQUENCE_DIR = baseline.SEQUENCE_DIR

COMMON_CONFIG = dict(
    baseline.COMMON_CONFIG
)


# ============================================================
# SCALABILITY OUTPUT ROOT
# ============================================================

OUTPUT_ROOT = (
    NEW_ROOT
    / "outputs"
    / "scalability"
)


# ============================================================
# REVIEWER-REQUESTED SCALABILITY PROTOCOL
# ============================================================

SCALABILITY_CONFIG: Dict[str, Any] = {

    # --------------------------------------------------------
    # Experiment identity
    # --------------------------------------------------------

    "experiment_family":
        "reviewer_requested_sacu_scalability",

    "new_experiment":
        True,

    "replaces_existing_manuscript_numbers":
        False,

    "result_policy":
        (
            "All values generated by this experiment family "
            "are new reviewer-requested scalability results. "
            "They do not replace or modify numerical values "
            "already reported in the submitted manuscript."
        ),


    # --------------------------------------------------------
    # Direct reviewer-requested dimensions
    # --------------------------------------------------------

    "reviewer_requested_dimensions": [

        "different_numbers_of_agents",

        "larger_domain_sizes",

        "varying_communication_costs",
    ],


    # --------------------------------------------------------
    # Actual SACU implementation
    # --------------------------------------------------------

    "implementation_module":
        "src.models_sacu",

    "implementation_class":
        "OrgSACUSolver",

    "training_module":
        "src.training.trainer_v2",

    "training_class":
        "TrainerV2",

    "deployment_function":
        "predict_sacu_deployment",

    "implementation_policy":
        (
            "All scalability experiments must execute the "
            "actual OrgSACUSolver implementation used by the "
            "manuscript. No MLP, PINN, MoE, FNO, DD-PINN, "
            "or other proxy model may be substituted."
        ),


    # --------------------------------------------------------
    # AGENT-COUNT SCALING
    #
    # Confirmed from OrgSACUSolver:
    #
    #   self.N = self.grid * self.grid
    #
    # Therefore only naturally supported square-grid agent
    # counts are used.
    # --------------------------------------------------------

    "agent_count_definition":
        "N = grid * grid",

    "agent_grids": [
        2,
        3,
        4,
        5,
    ],

    "agent_counts": [
        4,
        9,
        16,
        25,
    ],

    "reference_grid":
        4,

    "reference_agent_count":
        16,

    "agent_count_policy":
        (
            "Agent count follows the implemented "
            "OrgSACUSolver definition N = grid * grid. "
            "The sweep therefore uses grid values 2, 3, 4, "
            "and 5, corresponding to 4, 9, 16, and 25 SACUs. "
            "The existing 4x4 configuration with 16 SACUs "
            "is retained as the reference condition."
        ),


    # --------------------------------------------------------
    # DOMAIN-SIZE SCALING
    # --------------------------------------------------------

    "reference_domain_size": [
        128,
        128,
    ],

    "domain_sizes": [

        [
            64,
            64,
        ],

        [
            128,
            128,
        ],

        [
            256,
            256,
        ],
    ],

    "domain_size_policy":
        (
            "The current 128x128 domain is the reference. "
            "A 64x64 condition provides a smaller-domain "
            "computational reference, while 256x256 directly "
            "tests a larger domain. Predictive metrics may "
            "only be reported where physically valid paired "
            "target fields exist."
        ),

    "domain_scaling_metric_policy":
        (
            "If enlarged or reduced domains are created solely "
            "for computational scaling through deterministic "
            "resizing, replication, or interpolation, only "
            "latency, throughput, parameter count, and memory "
            "may be reported. MAE, RMSE, and physics residual "
            "must not be fabricated for such conditions."
        ),


    # --------------------------------------------------------
    # COMMUNICATION-COST SCALING
    # --------------------------------------------------------

    "communication_delay_ms": [
        0.0,
        1.0,
        5.0,
        10.0,
    ],

    "reference_communication_delay_ms":
        0.0,

    "communication_cost_policy":
        (
            "Communication-cost experiments must distinguish "
            "actual measured SACU computation time from "
            "deliberately injected communication delay. "
            "Injected delay values are controlled scenarios "
            "and must never be described as measured network "
            "latency."
        ),


    # --------------------------------------------------------
    # IMMUTABLE COMMON DATA PROTOCOL
    # --------------------------------------------------------

    "seed":
        COMMON_CONFIG[
            "seed"
        ],

    "train_fraction":
        COMMON_CONFIG[
            "train_fraction"
        ],

    "validation_fraction":
        COMMON_CONFIG[
            "validation_fraction"
        ],

    "test_fraction":
        COMMON_CONFIG[
            "test_fraction"
        ],

    "batch_size":
        COMMON_CONFIG[
            "batch_size"
        ],

    "epochs":
        COMMON_CONFIG[
            "epochs"
        ],

    "learning_rate":
        COMMON_CONFIG[
            "learning_rate"
        ],

    "optimizer":
        COMMON_CONFIG[
            "optimizer"
        ],

    "selection_metric":
        COMMON_CONFIG[
            "selection_metric"
        ],

    "test_policy":
        COMMON_CONFIG[
            "test_policy"
        ],


    # --------------------------------------------------------
    # PHYSICS / EVALUATION
    # --------------------------------------------------------

    "physics_operator":
        COMMON_CONFIG[
            "physics_operator"
        ],

    "use_common_wave_residual":
        COMMON_CONFIG[
            "use_common_wave_residual"
        ],

    "accuracy_metric_policy":
        (
            "MAE, RMSE, and wave residual are computed only "
            "for configurations having valid paired targets. "
            "Computational scaling configurations lacking valid "
            "ground truth are not assigned predictive metrics."
        ),


    # --------------------------------------------------------
    # LATENCY PROTOCOL
    # --------------------------------------------------------

    "latency_warmup_runs":
        COMMON_CONFIG[
            "latency_warmup_runs"
        ],

    "latency_measurement_runs":
        COMMON_CONFIG[
            "latency_measurement_runs"
        ],

    "timing_unit":
        "seconds",

    "measure_p50":
        True,

    "measure_p95":
        True,

    "measure_p99":
        True,


    # --------------------------------------------------------
    # COMPUTATIONAL METRICS
    # --------------------------------------------------------

    "computational_metrics": [

        "parameter_count",

        "inference_latency_mean",

        "inference_latency_p50",

        "inference_latency_p95",

        "inference_latency_p99",

        "throughput_sequences_per_sec",

        "peak_gpu_memory_bytes",
    ],


    # --------------------------------------------------------
    # SCIENTIFIC INTEGRITY
    # --------------------------------------------------------

    "data_policy":
        (
            "All experiments inherit the fixed 70/15/15 "
            "sequence split from the validated baseline "
            "protocol. No scaling condition may be selected "
            "using held-out test performance."
        ),

    "deterministic":
        True,

    "configuration_freeze_policy":
        (
            "For each scalability axis, only the variable under "
            "study may change. All remaining SACU architecture, "
            "training, physics, influence-weighting, role, and "
            "communication settings must remain fixed to the "
            "validated reference implementation unless the "
            "reviewer-requested variable itself requires change."
        ),
}


# ============================================================
# RE-EXPORT VALIDATED METRICS
# ============================================================

mae = baseline.mae
rmse = baseline.rmse

wave_residual_mean = (
    baseline.wave_residual_mean
)

count_trainable_parameters = (
    baseline.count_trainable_parameters
)

is_better_checkpoint = (
    baseline.is_better_checkpoint
)


# ============================================================
# DETERMINISM
# ============================================================

def set_determinism(
    seed: Optional[int] = None,
) -> None:

    if seed is None:

        seed = int(
            SCALABILITY_CONFIG[
                "seed"
            ]
        )


    np.random.seed(
        seed
    )

    tf.random.set_seed(
        seed
    )


    try:

        tf.config.experimental.enable_op_determinism()

        print(
            "[INFO] TensorFlow deterministic "
            "operations enabled."
        )

    except Exception as exc:

        print(
            "[WARNING] TensorFlow deterministic "
            "operations could not be enabled:"
        )

        print(
            exc
        )


# ============================================================
# NATURAL SORTING
# ============================================================

def natural_sort_key(
    path: Path,
):

    parts = re.split(
        r"(\d+)",
        path.name,
    )


    return [

        int(part)
        if part.isdigit()
        else part.lower()

        for part in parts
    ]


# ============================================================
# SEQUENCE DISCOVERY
# ============================================================

def list_sequence_files() -> List[Path]:

    if not SEQUENCE_DIR.exists():

        raise FileNotFoundError(
            "Sequence directory does not exist:\n"
            f"{SEQUENCE_DIR}"
        )


    files = sorted(

        SEQUENCE_DIR.glob(
            "*.npz"
        ),

        key=
            natural_sort_key,
    )


    if not files:

        raise FileNotFoundError(
            "No NPZ sequence files were found in:\n"
            f"{SEQUENCE_DIR}"
        )


    return files


# ============================================================
# FIXED 70 / 15 / 15 SPLIT
# ============================================================

def split_sequence_files(
    files: Optional[
        Sequence[Path]
    ] = None,
):

    if files is None:

        files = (
            list_sequence_files()
        )


    files = list(
        files
    )


    n_total = len(
        files
    )


    n_train = int(
        n_total
        * float(
            SCALABILITY_CONFIG[
                "train_fraction"
            ]
        )
    )


    n_validation = int(
        n_total
        * float(
            SCALABILITY_CONFIG[
                "validation_fraction"
            ]
        )
    )


    n_test = (
        n_total
        - n_train
        - n_validation
    )


    if (
        n_train <= 0
        or n_validation <= 0
        or n_test <= 0
    ):

        raise RuntimeError(
            "Invalid train/validation/test split.\n"
            f"Total: {n_total}\n"
            f"Train: {n_train}\n"
            f"Validation: {n_validation}\n"
            f"Test: {n_test}"
        )


    train_files = files[
        :n_train
    ]


    validation_files = files[
        n_train:
        n_train + n_validation
    ]


    test_files = files[
        n_train + n_validation:
    ]


    validate_split_integrity(
        train_files,
        validation_files,
        test_files,
    )


    return (
        train_files,
        validation_files,
        test_files,
    )


# ============================================================
# SPLIT INTEGRITY
# ============================================================

def validate_split_integrity(
    train_files: Sequence[Path],
    validation_files: Sequence[Path],
    test_files: Sequence[Path],
) -> None:

    train_set = {
        str(
            path.resolve()
        )
        for path
        in train_files
    }


    validation_set = {
        str(
            path.resolve()
        )
        for path
        in validation_files
    }


    test_set = {
        str(
            path.resolve()
        )
        for path
        in test_files
    }


    if train_set & validation_set:

        raise RuntimeError(
            "Train/validation leakage detected."
        )


    if train_set & test_set:

        raise RuntimeError(
            "Train/test leakage detected."
        )


    if validation_set & test_set:

        raise RuntimeError(
            "Validation/test leakage detected."
        )


# ============================================================
# SPLIT FINGERPRINT
# ============================================================

def split_fingerprint(
    files: Sequence[Path],
) -> str:

    payload = "\n".join(
        path.name
        for path
        in files
    )


    return hashlib.sha256(
        payload.encode(
            "utf-8"
        )
    ).hexdigest()


# ============================================================
# SLUG
# ============================================================

def slugify(
    value: str,
) -> str:

    value = value.strip().lower()


    value = re.sub(
        r"[^a-z0-9]+",
        "_",
        value,
    )


    value = value.strip(
        "_"
    )


    return (
        value
        if value
        else "scalability_experiment"
    )


# ============================================================
# JSON SERIALIZATION
# ============================================================

def to_json_serializable(
    value: Any,
) -> Any:

    if isinstance(
        value,
        Path,
    ):

        return str(
            value
        )


    if isinstance(
        value,
        np.generic,
    ):

        return value.item()


    if isinstance(
        value,
        np.ndarray,
    ):

        return value.tolist()


    if isinstance(
        value,
        dict,
    ):

        return {

            str(key):
                to_json_serializable(
                    item
                )

            for key, item
            in value.items()
        }


    if isinstance(
        value,
        (
            list,
            tuple,
        ),
    ):

        return [

            to_json_serializable(
                item
            )

            for item in value
        ]


    return value


# ============================================================
# SAVE JSON
# ============================================================

def save_json(
    path: Path | str,
    data: Any,
) -> None:

    path = Path(
        path
    )


    path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )


    with path.open(
        "w",
        encoding="utf-8",
    ) as file:

        json.dump(

            to_json_serializable(
                data
            ),

            file,

            indent=2,

            ensure_ascii=False,
        )


# ============================================================
# SAVE CSV
# ============================================================

def save_csv(
    path: Path | str,
    rows: Iterable[
        Dict[str, Any]
    ],
) -> None:

    path = Path(
        path
    )


    rows = list(
        rows
    )


    path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )


    if not rows:

        path.write_text(
            "",
            encoding="utf-8",
        )

        return


    fieldnames = []

    seen = set()


    for row in rows:

        for key in row.keys():

            if key not in seen:

                seen.add(
                    key
                )

                fieldnames.append(
                    key
                )


    with path.open(
        "w",
        newline="",
        encoding="utf-8",
    ) as file:

        writer = csv.DictWriter(
            file,
            fieldnames=fieldnames,
        )


        writer.writeheader()


        for row in rows:

            writer.writerow(
                {
                    key:
                        to_json_serializable(
                            row.get(
                                key,
                                "",
                            )
                        )

                    for key
                    in fieldnames
                }
            )


# ============================================================
# ENVIRONMENT METADATA
# ============================================================

def environment_metadata() -> Dict[
    str,
    Any,
]:

    gpu_devices = (
        tf.config.list_physical_devices(
            "GPU"
        )
    )


    return {

        "python_version":
            sys.version,

        "tensorflow_version":
            tf.__version__,

        "platform":
            platform.platform(),

        "system":
            platform.system(),

        "machine":
            platform.machine(),

        "processor":
            platform.processor(),

        "hostname":
            socket.gethostname(),

        "working_directory":
            str(
                Path.cwd()
            ),

        "protocol_file":
            str(
                THIS_FILE
            ),

        "validated_baseline_protocol":
            str(
                BASELINE_PROTOCOL_PATH
            ),

        "gpu_available":
            bool(
                gpu_devices
            ),

        "gpu_devices":
            [
                str(
                    device
                )
                for device
                in gpu_devices
            ],

        "cuda_build":
            bool(
                tf.test.is_built_with_cuda()
            ),
    }


# ============================================================
# GPU MEMORY HELPERS
# ============================================================

def reset_gpu_memory_stats() -> None:

    gpu_devices = (
        tf.config.list_physical_devices(
            "GPU"
        )
    )


    if not gpu_devices:

        return


    try:

        tf.config.experimental.reset_memory_stats(
            "GPU:0"
        )

    except Exception:

        pass


def gpu_memory_info() -> Dict[
    str,
    Any,
]:

    gpu_devices = (
        tf.config.list_physical_devices(
            "GPU"
        )
    )


    if not gpu_devices:

        return {

            "available":
                False,

            "current_bytes":
                None,

            "peak_bytes":
                None,
        }


    try:

        info = (
            tf.config.experimental.get_memory_info(
                "GPU:0"
            )
        )


        return {

            "available":
                True,

            "current_bytes":
                int(
                    info[
                        "current"
                    ]
                ),

            "peak_bytes":
                int(
                    info[
                        "peak"
                    ]
                ),
        }


    except Exception:

        return {

            "available":
                True,

            "current_bytes":
                None,

            "peak_bytes":
                None,
        }


# ============================================================
# TIMING SUMMARY
# ============================================================

def summarize_timings(
    timings: Sequence[float],
) -> Dict[str, float]:

    values = np.asarray(
        timings,
        dtype=np.float64,
    )


    if values.size == 0:

        raise ValueError(
            "No timing values supplied."
        )


    return {

        "runs":
            int(
                values.size
            ),

        "mean_sec":
            float(
                np.mean(
                    values
                )
            ),

        "std_sec":
            (
                float(
                    np.std(
                        values,
                        ddof=1,
                    )
                )
                if values.size > 1
                else 0.0
            ),

        "p50_sec":
            float(
                np.percentile(
                    values,
                    50,
                )
            ),

        "p95_sec":
            float(
                np.percentile(
                    values,
                    95,
                )
            ),

        "p99_sec":
            float(
                np.percentile(
                    values,
                    99,
                )
            ),

        "minimum_sec":
            float(
                np.min(
                    values
                )
            ),

        "maximum_sec":
            float(
                np.max(
                    values
                )
            ),
    }


# ============================================================
# SACU IMPLEMENTATION INVENTORY
#
# This is only a diagnostic/inventory function.
# Actual scalability scripts explicitly import:
#
#   src.models_sacu.OrgSACUSolver
#
# ============================================================

SEARCH_TERMS = [

    "sacu",

    "orgsacusolver",

    "agent",

    "communication",

    "coordination",

    "organizational",

    "specialization",

    "influence",
]


SKIP_DIRECTORIES = {

    ".git",

    ".venv",

    ".venv_gpu",

    "__pycache__",

    "outputs",

    "venv",

    "node_modules",
}


def should_skip_path(
    path: Path,
) -> bool:

    if any(
        part in SKIP_DIRECTORIES
        for part in path.parts
    ):

        return True


    # Do not let scalability scripts identify themselves
    # as candidate SACU implementations.

    if EXPERIMENT_DIR in path.parents:

        return True


    return False


def source_candidate_score(
    path: Path,
):

    try:

        text = path.read_text(
            encoding="utf-8",
            errors="ignore",
        ).lower()

    except Exception:

        return (
            0,
            [],
        )


    matched = []


    for term in SEARCH_TERMS:

        if term in text:

            matched.append(
                term
            )


    score = len(
        matched
    )


    if "orgsacusolver" in matched:

        score += 20


    elif "sacu" in matched:

        score += 10


    if "class " in text:

        score += 1


    if (
        "def call(" in text
        or "def predict(" in text
        or "def forward(" in text
    ):

        score += 1


    return (
        score,
        matched,
    )


def find_sacu_implementation_candidates(
    max_results: int = 30,
):

    roots = []


    src_dir = (
        NEW_ROOT
        / "src"
    )


    if src_dir.exists():

        roots.append(
            src_dir
        )


    roots.append(
        NEW_ROOT
    )


    seen = set()

    candidates = []


    for root in roots:

        for path in root.rglob(
            "*.py"
        ):

            if should_skip_path(
                path
            ):

                continue


            resolved = str(
                path.resolve()
            )


            if resolved in seen:

                continue


            seen.add(
                resolved
            )


            (
                score,
                matched,
            ) = source_candidate_score(
                path
            )


            if score <= 0:

                continue


            try:

                relative_path = str(
                    path.relative_to(
                        NEW_ROOT
                    )
                )

            except ValueError:

                relative_path = str(
                    path
                )


            candidates.append(
                {

                    "score":
                        score,

                    "path":
                        str(
                            path
                        ),

                    "relative_path":
                        relative_path,

                    "matched_terms":
                        matched,
                }
            )


    candidates.sort(

        key=lambda item:
            (
                -item[
                    "score"
                ],
                item[
                    "relative_path"
                ],
            )
    )


    return candidates[
        :max_results
    ]


# ============================================================
# OPTIONAL EXPLICIT IMPLEMENTATION OVERRIDE
# ============================================================

def explicit_sacu_module_path() -> Optional[Path]:

    value = os.environ.get(
        "SACU_SCALABILITY_MODULE"
    )


    if not value:

        return None


    path = Path(
        value
    ).expanduser()


    if not path.is_absolute():

        path = (
            NEW_ROOT
            / path
        )


    path = path.resolve()


    if not path.exists():

        raise FileNotFoundError(
            "SACU_SCALABILITY_MODULE points "
            "to a missing file:\n"
            f"{path}"
        )


    return path


# ============================================================
# INITIALIZE SCALABILITY RUN
# ============================================================

def initialize_scalability_run(
    experiment_name: str,
    experiment_config: Dict[
        str,
        Any,
    ],
):

    set_determinism()


    all_files = (
        list_sequence_files()
    )


    (
        train_files,
        validation_files,
        test_files,
    ) = split_sequence_files(
        all_files
    )


    timestamp = datetime.now().strftime(
        "%Y%m%d-%H%M%S"
    )


    slug = slugify(
        experiment_name
    )


    run_name = (
        f"{slug}_{timestamp}"
    )


    run_dir = (
        OUTPUT_ROOT
        / slug
        / run_name
    )


    tables_dir = (
        run_dir
        / "tables"
    )


    logs_dir = (
        run_dir
        / "logs"
    )


    figures_dir = (
        run_dir
        / "figures"
    )


    models_dir = (
        run_dir
        / "models"
    )


    for directory in [

        run_dir,

        tables_dir,

        logs_dir,

        figures_dir,

        models_dir,

    ]:

        directory.mkdir(
            parents=True,
            exist_ok=True,
        )


    split_manifest = {

        "total_sequences":
            len(
                all_files
            ),

        "train_count":
            len(
                train_files
            ),

        "validation_count":
            len(
                validation_files
            ),

        "test_count":
            len(
                test_files
            ),

        "train_fingerprint":
            split_fingerprint(
                train_files
            ),

        "validation_fingerprint":
            split_fingerprint(
                validation_files
            ),

        "test_fingerprint":
            split_fingerprint(
                test_files
            ),

        "train_files":
            [
                path.name
                for path
                in train_files
            ],

        "validation_files":
            [
                path.name
                for path
                in validation_files
            ],

        "test_files":
            [
                path.name
                for path
                in test_files
            ],
    }


    complete_config = {

        "experiment_name":
            experiment_name,

        "run_name":
            run_name,

        "scalability_protocol":
            SCALABILITY_CONFIG,

        "common_baseline_config":
            COMMON_CONFIG,

        "experiment_config":
            experiment_config,

        "environment":
            environment_metadata(),

        "split_summary": {

            "total":
                len(
                    all_files
                ),

            "train":
                len(
                    train_files
                ),

            "validation":
                len(
                    validation_files
                ),

            "test":
                len(
                    test_files
                ),
        },
    }


    save_json(
        run_dir
        / "config.json",
        complete_config,
    )


    save_json(
        run_dir
        / "split_manifest.json",
        split_manifest,
    )


    split_rows = []


    for split_name, files in [

        (
            "train",
            train_files,
        ),

        (
            "validation",
            validation_files,
        ),

        (
            "test",
            test_files,
        ),

    ]:

        for index, path in enumerate(
            files
        ):

            split_rows.append(
                {

                    "split":
                        split_name,

                    "split_index":
                        index,

                    "filename":
                        path.name,

                    "path":
                        str(
                            path
                        ),
                }
            )


    save_csv(
        tables_dir
        / "split_manifest.csv",
        split_rows,
    )


    return {

        "run_dir":
            run_dir,

        "tables_dir":
            tables_dir,

        "logs_dir":
            logs_dir,

        "figures_dir":
            figures_dir,

        "models_dir":
            models_dir,

        "all_files":
            all_files,

        "train_files":
            train_files,

        "validation_files":
            validation_files,

        "test_files":
            test_files,

        "config":
            complete_config,

        "split_manifest":
            split_manifest,
    }


# ============================================================
# AGENT GRID CONSISTENCY
# ============================================================

def validate_agent_grid_protocol() -> None:

    grids = (
        SCALABILITY_CONFIG[
            "agent_grids"
        ]
    )


    counts = (
        SCALABILITY_CONFIG[
            "agent_counts"
        ]
    )


    if len(
        grids
    ) != len(
        counts
    ):

        raise RuntimeError(
            "agent_grids and agent_counts "
            "must have equal lengths."
        )


    expected_counts = [
        int(
            grid
        )
        *
        int(
            grid
        )

        for grid in grids
    ]


    if expected_counts != counts:

        raise RuntimeError(
            "Agent-count protocol is inconsistent "
            "with OrgSACUSolver N = grid * grid.\n"
            f"Grids: {grids}\n"
            f"Expected counts: {expected_counts}\n"
            f"Configured counts: {counts}"
        )


    reference_grid = int(
        SCALABILITY_CONFIG[
            "reference_grid"
        ]
    )


    reference_agents = int(
        SCALABILITY_CONFIG[
            "reference_agent_count"
        ]
    )


    if (
        reference_grid
        * reference_grid
        != reference_agents
    ):

        raise RuntimeError(
            "Reference agent count is inconsistent "
            "with reference grid."
        )


# ============================================================
# PROTOCOL SELF-TEST
# ============================================================

def protocol_self_test() -> None:

    set_determinism()


    validate_agent_grid_protocol()


    files = (
        list_sequence_files()
    )


    (
        train_files,
        validation_files,
        test_files,
    ) = split_sequence_files(
        files
    )


    candidates = (
        find_sacu_implementation_candidates()
    )


    explicit_module = (
        explicit_sacu_module_path()
    )


    print()
    print("=" * 80)

    print(
        "SACU SCALABILITY PROTOCOL SELF-TEST"
    )

    print("=" * 80)


    print(
        "Project root:"
    )

    print(
        NEW_ROOT
    )


    print()


    print(
        "Sequence directory:"
    )

    print(
        SEQUENCE_DIR
    )


    print()


    print(
        "Sequences:"
    )

    print(
        f"  Total      : {len(files)}"
    )

    print(
        f"  Train      : {len(train_files)}"
    )

    print(
        f"  Validation : {len(validation_files)}"
    )

    print(
        f"  Test       : {len(test_files)}"
    )


    print()


    print(
        "Split fingerprints:"
    )

    print(
        "  Train      :",
        split_fingerprint(
            train_files
        )[:16],
    )

    print(
        "  Validation :",
        split_fingerprint(
            validation_files
        )[:16],
    )

    print(
        "  Test       :",
        split_fingerprint(
            test_files
        )[:16],
    )


    print()
    print("=" * 80)

    print(
        "REVIEWER-REQUESTED SCALABILITY DIMENSIONS"
    )

    print("=" * 80)


    for item in SCALABILITY_CONFIG[
        "reviewer_requested_dimensions"
    ]:

        print(
            f"  - {item}"
        )


    print()
    print("=" * 80)

    print(
        "AGENT-COUNT SCALING"
    )

    print("=" * 80)


    for (
        grid,
        agent_count,
    ) in zip(

        SCALABILITY_CONFIG[
            "agent_grids"
        ],

        SCALABILITY_CONFIG[
            "agent_counts"
        ],
    ):

        reference_marker = (
            "  <-- reference"
            if grid
            == SCALABILITY_CONFIG[
                "reference_grid"
            ]
            else ""
        )


        print(
            f"  grid={grid} "
            f"-> {agent_count} SACUs"
            f"{reference_marker}"
        )


    print()


    print(
        "Agent-count definition:"
    )

    print(
        "  N = grid * grid"
    )


    print()
    print("=" * 80)

    print(
        "DOMAIN-SIZE SCALING"
    )

    print("=" * 80)


    for size in SCALABILITY_CONFIG[
        "domain_sizes"
    ]:

        reference_marker = (
            "  <-- reference"
            if size
            == SCALABILITY_CONFIG[
                "reference_domain_size"
            ]
            else ""
        )


        print(
            f"  {size[0]} x {size[1]}"
            f"{reference_marker}"
        )


    print()
    print("=" * 80)

    print(
        "COMMUNICATION-COST SCALING"
    )

    print("=" * 80)


    for delay in SCALABILITY_CONFIG[
        "communication_delay_ms"
    ]:

        reference_marker = (
            "  <-- reference"
            if delay
            == SCALABILITY_CONFIG[
                "reference_communication_delay_ms"
            ]
            else ""
        )


        print(
            f"  {delay:.1f} ms"
            f"{reference_marker}"
        )


    print()
    print("=" * 80)

    print(
        "IMPLEMENTATION"
    )

    print("=" * 80)


    print(
        "Model module:"
    )

    print(
        "  src.models_sacu"
    )


    print(
        "Model class:"
    )

    print(
        "  OrgSACUSolver"
    )


    print(
        "Trainer:"
    )

    print(
        "  src.training.trainer_v2.TrainerV2"
    )


    print(
        "Deployment:"
    )

    print(
        "  predict_sacu_deployment"
    )


    print()


    if explicit_module is not None:

        print(
            "Explicit SACU module override:"
        )

        print(
            explicit_module
        )

    else:

        print(
            "SACU_SCALABILITY_MODULE:"
        )

        print(
            "  not required; implementation is now explicitly known"
        )


    print()
    print("=" * 80)

    print(
        "SACU IMPLEMENTATION INVENTORY"
    )

    print("=" * 80)


    if not candidates:

        print(
            "No candidate source files were found."
        )

    else:

        for index, candidate in enumerate(
            candidates,
            start=1,
        ):

            print(
                f"{index:2d}. "
                f"score={candidate['score']:2d} | "
                f"{candidate['relative_path']}"
            )


            print(
                "    matched:",
                ", ".join(
                    candidate[
                        "matched_terms"
                    ]
                ),
            )


    inventory_dir = (
        OUTPUT_ROOT
        / "protocol_inventory"
    )


    inventory_dir.mkdir(
        parents=True,
        exist_ok=True,
    )


    save_json(
        inventory_dir
        / "sacu_implementation_candidates.json",

        {

            "known_model_module":
                "src.models_sacu",

            "known_model_class":
                "OrgSACUSolver",

            "known_training_module":
                "src.training.trainer_v2",

            "known_training_class":
                "TrainerV2",

            "known_deployment_function":
                "predict_sacu_deployment",

            "explicit_module_override":
                explicit_module,

            "candidates":
                candidates,
        },
    )


    save_csv(
        inventory_dir
        / "sacu_implementation_candidates.csv",
        candidates,
    )


    print()
    print("=" * 80)

    print(
        "EXECUTION ENVIRONMENT"
    )

    print("=" * 80)


    print(
        "TensorFlow version:",
        tf.__version__,
    )


    print(
        "CUDA build:",
        tf.test.is_built_with_cuda(),
    )


    print(
        "GPU devices:",
        tf.config.list_physical_devices(
            "GPU"
        ),
    )


    print()
    print("=" * 80)

    print(
        "PROTOCOL STATUS"
    )

    print("=" * 80)


    print(
        "PASS: scalability experiment protocol is fixed."
    )


    print(
        "PASS: actual SACU implementation is identified as "
        "src.models_sacu.OrgSACUSolver."
    )


    print(
        "PASS: agent count follows the implemented "
        "N = grid * grid definition."
    )


    print(
        "PASS: predefined agent conditions are "
        "4, 9, 16, and 25 SACUs."
    )


    print(
        "PASS: 16 SACUs remain the reference condition."
    )


    print(
        "PASS: domain conditions are "
        "64x64, 128x128, and 256x256."
    )


    print(
        "PASS: communication-delay conditions are "
        "0, 1, 5, and 10 ms."
    )


    print(
        "PASS: no existing manuscript numerical value "
        "will be modified."
    )


    print(
        "READY: proceed to 01_agent_count_scaling.py."
    )


# ============================================================
# ENTRY POINT
# ============================================================

if __name__ == "__main__":

    protocol_self_test()