from __future__ import annotations

import csv
import hashlib
import importlib.util
import json
import os
import platform
import re
import socket
import sys
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, Iterable, List, Sequence, Tuple

import numpy as np
import tensorflow as tf


# ============================================================
# PATHS
# ============================================================

THIS_FILE = Path(__file__).resolve()

EXPERIMENT_DIR = THIS_FILE.parent
EXPERIMENTS_ROOT = EXPERIMENT_DIR.parent
NEW_ROOT = EXPERIMENTS_ROOT.parent

BASELINE_PROTOCOL_PATH = (
    EXPERIMENTS_ROOT
    / "03_baseline_comparison"
    / "00_common_protocol.py"
)


# ============================================================
# LOAD THE VALIDATED COMMON BASELINE PROTOCOL
# ============================================================

if not BASELINE_PROTOCOL_PATH.exists():

    raise FileNotFoundError(
        "Validated baseline protocol was not found:\n"
        f"{BASELINE_PROTOCOL_PATH}"
    )


spec = importlib.util.spec_from_file_location(
    "validated_baseline_protocol",
    BASELINE_PROTOCOL_PATH,
)

if spec is None or spec.loader is None:

    raise ImportError(
        "Unable to load validated baseline protocol:\n"
        f"{BASELINE_PROTOCOL_PATH}"
    )


baseline = importlib.util.module_from_spec(
    spec
)

spec.loader.exec_module(
    baseline
)


# ============================================================
# AUTHORITATIVE PATHS FROM VALIDATED BASELINE PROTOCOL
# ============================================================

ORIGINAL_ROOT = baseline.ORIGINAL_ROOT
NEW_ROOT = baseline.NEW_ROOT
DATA_ROOT = baseline.DATA_ROOT
SEQUENCE_DIR = baseline.SEQUENCE_DIR


# ============================================================
# INHERIT THE IMMUTABLE COMMON EXPERIMENTAL CONFIGURATION
# ============================================================

COMMON_CONFIG = dict(
    baseline.COMMON_CONFIG
)


# ============================================================
# MODERN-BASELINE PROTOCOL
# ============================================================

REFERENCE_PARAMETER_COUNT = 198401

OPERATOR_CONFIG: Dict[str, Any] = {

    # --------------------------------------------------------
    # Experiment identity
    # --------------------------------------------------------

    "experiment_family":
        "reviewer_requested_modern_baseline_comparison",

    "new_experiment":
        True,

    "replaces_existing_manuscript_numbers":
        False,

    "scientific_status":
        (
            "All numerical values generated by this experiment "
            "family are new reviewer-requested experimental "
            "results. They do not replace or modify numerical "
            "values already reported in the submitted manuscript."
        ),


    # --------------------------------------------------------
    # Models required by reviewers
    # --------------------------------------------------------

    "planned_models": [

        "Fourier Neural Operator",

        "Domain-Decomposed Physics-Informed Neural Network",
    ],


    # --------------------------------------------------------
    # Capacity matching
    # --------------------------------------------------------

    "reference_parameter_count":
        REFERENCE_PARAMETER_COUNT,

    "reference_architecture":
        "MLP_4x256_and_PINN_4x256",

    "parameter_budget_policy":
        (
            "Modern comparator capacity should be kept as close "
            "as technically practical to the 198401-parameter "
            "MLP/PINN reference budget."
        ),

    # We do not silently accept a huge model.
    # This can be overridden explicitly by a model script only
    # if a technical reason is documented in that run.
    "default_parameter_tolerance_fraction":
        0.15,


    # --------------------------------------------------------
    # Immutable data protocol
    # --------------------------------------------------------

    "dataset_source":
        str(
            SEQUENCE_DIR
        ),

    "split_policy":
        "same_sorted_70_15_15_sequence_split_as_baseline_suite",

    "train_fraction":
        COMMON_CONFIG[
            "train_fraction"
        ],

    "validation_fraction":
        COMMON_CONFIG[
            "validation_fraction"
        ],

    "test_fraction":
        COMMON_CONFIG[
            "test_fraction"
        ],

    "seed":
        COMMON_CONFIG[
            "seed"
        ],


    # --------------------------------------------------------
    # Inputs / targets
    # --------------------------------------------------------

    "input_channels":
        COMMON_CONFIG[
            "input_channels"
        ],

    "output_channels":
        COMMON_CONFIG[
            "output_channels"
        ],

    "input_semantics":
        COMMON_CONFIG[
            "input_semantics"
        ],

    "target_semantics":
        COMMON_CONFIG[
            "target_semantics"
        ],


    # --------------------------------------------------------
    # Training budget
    # --------------------------------------------------------

    "batch_size":
        COMMON_CONFIG[
            "batch_size"
        ],

    "epochs":
        COMMON_CONFIG[
            "epochs"
        ],

    "learning_rate":
        COMMON_CONFIG[
            "learning_rate"
        ],

    "optimizer":
        COMMON_CONFIG[
            "optimizer"
        ],


    # --------------------------------------------------------
    # Physics protocol
    # --------------------------------------------------------

    "physics_operator":
        COMMON_CONFIG[
            "physics_operator"
        ],

    "use_common_wave_residual":
        COMMON_CONFIG[
            "use_common_wave_residual"
        ],

    "physics_metric_policy":
        (
            "Every modern baseline is evaluated using exactly "
            "the same second-order wave-equation residual "
            "implemented by the validated baseline protocol."
        ),


    # --------------------------------------------------------
    # Evaluation
    # --------------------------------------------------------

    "metrics":
        list(
            COMMON_CONFIG[
                "metrics"
            ]
        ),

    "selection_metric":
        COMMON_CONFIG[
            "selection_metric"
        ],

    "test_policy":
        COMMON_CONFIG[
            "test_policy"
        ],

    "latency_warmup_runs":
        COMMON_CONFIG[
            "latency_warmup_runs"
        ],

    "latency_measurement_runs":
        COMMON_CONFIG[
            "latency_measurement_runs"
        ],


    # --------------------------------------------------------
    # Result handling
    # --------------------------------------------------------

    "raw_output_policy":
        (
            "Every run must preserve configuration, split "
            "manifest, checkpoint, per-sample results, summary "
            "metrics, timing results, and model parameter count."
        ),

    "result_policy":
        (
            "Only values actually generated by executable "
            "experiments may be included in reviewer responses "
            "or manuscript additions."
        ),
}


# ============================================================
# OUTPUT ROOT
# ============================================================

OUTPUT_ROOT = (
    NEW_ROOT
    / "outputs"
    / "modern_baselines"
)


# ============================================================
# RE-EXPORT VALIDATED METRIC FUNCTIONS
# ============================================================

mae = baseline.mae
rmse = baseline.rmse

wave_residual_mean = (
    baseline.wave_residual_mean
)

count_trainable_parameters = (
    baseline.count_trainable_parameters
)

is_better_checkpoint = (
    baseline.is_better_checkpoint
)


# ============================================================
# DETERMINISM
# ============================================================

def set_determinism(
    seed: int | None = None,
) -> None:

    if seed is None:

        seed = int(
            OPERATOR_CONFIG[
                "seed"
            ]
        )


    np.random.seed(
        seed
    )

    tf.random.set_seed(
        seed
    )


    try:

        tf.config.experimental.enable_op_determinism()

        print(
            "[INFO] TensorFlow deterministic "
            "operations enabled."
        )

    except Exception as exc:

        print(
            "[WARNING] TensorFlow deterministic "
            "operations could not be enabled:"
        )

        print(
            exc
        )


# ============================================================
# NATURAL FILE SORTING
# ============================================================

def natural_sort_key(
    path: Path,
):

    parts = re.split(
        r"(\d+)",
        path.name,
    )

    return [

        int(part)
        if part.isdigit()
        else part.lower()

        for part in parts
    ]


# ============================================================
# SEQUENCE DISCOVERY
# ============================================================

def list_sequence_files() -> List[Path]:

    if not SEQUENCE_DIR.exists():

        raise FileNotFoundError(
            "Sequence directory does not exist:\n"
            f"{SEQUENCE_DIR}"
        )


    sequence_files = sorted(

        SEQUENCE_DIR.glob(
            "*.npz"
        ),

        key=
            natural_sort_key,
    )


    if not sequence_files:

        raise FileNotFoundError(
            "No NPZ sequence files were found in:\n"
            f"{SEQUENCE_DIR}"
        )


    return sequence_files


# ============================================================
# IMMUTABLE 70 / 15 / 15 SPLIT
# ============================================================

def split_sequence_files(
    sequence_files: Sequence[Path] | None = None,
) -> Tuple[
    List[Path],
    List[Path],
    List[Path],
]:

    if sequence_files is None:

        sequence_files = (
            list_sequence_files()
        )


    sequence_files = list(
        sequence_files
    )


    n_total = len(
        sequence_files
    )


    train_fraction = float(
        OPERATOR_CONFIG[
            "train_fraction"
        ]
    )

    validation_fraction = float(
        OPERATOR_CONFIG[
            "validation_fraction"
        ]
    )


    n_train = int(
        n_total
        * train_fraction
    )

    n_validation = int(
        n_total
        * validation_fraction
    )


    n_test = (
        n_total
        - n_train
        - n_validation
    )


    if (
        n_train <= 0
        or n_validation <= 0
        or n_test <= 0
    ):

        raise ValueError(
            "Invalid train/validation/test split.\n"
            f"Total: {n_total}\n"
            f"Train: {n_train}\n"
            f"Validation: {n_validation}\n"
            f"Test: {n_test}"
        )


    train_files = sequence_files[
        :n_train
    ]

    validation_files = sequence_files[
        n_train:
        n_train + n_validation
    ]

    test_files = sequence_files[
        n_train + n_validation:
    ]


    return (
        train_files,
        validation_files,
        test_files,
    )


# ============================================================
# SPLIT VALIDATION
# ============================================================

def validate_split_integrity(
    train_files: Sequence[Path],
    validation_files: Sequence[Path],
    test_files: Sequence[Path],
) -> None:

    train_set = {
        str(path.resolve())
        for path in train_files
    }

    validation_set = {
        str(path.resolve())
        for path in validation_files
    }

    test_set = {
        str(path.resolve())
        for path in test_files
    }


    overlap_train_validation = (
        train_set
        & validation_set
    )

    overlap_train_test = (
        train_set
        & test_set
    )

    overlap_validation_test = (
        validation_set
        & test_set
    )


    if (
        overlap_train_validation
        or overlap_train_test
        or overlap_validation_test
    ):

        raise RuntimeError(
            "Sequence-level leakage detected "
            "between experimental partitions."
        )


# ============================================================
# SPLIT FINGERPRINT
# ============================================================

def split_fingerprint(
    files: Sequence[Path],
) -> str:

    payload = "\n".join(
        path.name
        for path in files
    )

    return hashlib.sha256(
        payload.encode(
            "utf-8"
        )
    ).hexdigest()


# ============================================================
# SLUG
# ============================================================

def slugify(
    value: str,
) -> str:

    value = value.strip().lower()

    value = re.sub(
        r"[^a-z0-9]+",
        "_",
        value,
    )

    value = value.strip(
        "_"
    )

    if not value:

        value = "experiment"

    return value


# ============================================================
# JSON CONVERSION
# ============================================================

def to_json_serializable(
    value: Any,
) -> Any:

    if isinstance(
        value,
        Path,
    ):

        return str(
            value
        )


    if isinstance(
        value,
        np.generic,
    ):

        return value.item()


    if isinstance(
        value,
        np.ndarray,
    ):

        return value.tolist()


    if isinstance(
        value,
        dict,
    ):

        return {

            str(key):
                to_json_serializable(
                    item
                )

            for key, item
            in value.items()
        }


    if isinstance(
        value,
        (
            list,
            tuple,
        ),
    ):

        return [

            to_json_serializable(
                item
            )

            for item in value
        ]


    return value


# ============================================================
# SAVE JSON
# ============================================================

def save_json(
    path: Path | str,
    data: Any,
) -> None:

    path = Path(
        path
    )


    path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )


    with path.open(
        "w",
        encoding="utf-8",
    ) as file:

        json.dump(

            to_json_serializable(
                data
            ),

            file,

            indent=2,

            ensure_ascii=False,
        )


# ============================================================
# SAVE CSV
# ============================================================

def save_csv(
    path: Path | str,
    rows: Iterable[Dict[str, Any]],
) -> None:

    path = Path(
        path
    )


    rows = list(
        rows
    )


    path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )


    if not rows:

        path.write_text(
            "",
            encoding="utf-8",
        )

        return


    fieldnames = []

    seen = set()


    for row in rows:

        for key in row.keys():

            if key not in seen:

                seen.add(
                    key
                )

                fieldnames.append(
                    key
                )


    with path.open(
        "w",
        newline="",
        encoding="utf-8",
    ) as file:

        writer = csv.DictWriter(
            file,
            fieldnames=fieldnames,
        )


        writer.writeheader()


        for row in rows:

            writer.writerow(
                {
                    key:
                        to_json_serializable(
                            row.get(
                                key,
                                "",
                            )
                        )

                    for key
                    in fieldnames
                }
            )


# ============================================================
# HARDWARE / SOFTWARE METADATA
# ============================================================

def environment_metadata() -> Dict[str, Any]:

    gpu_devices = (
        tf.config.list_physical_devices(
            "GPU"
        )
    )


    return {

        "python_version":
            sys.version,

        "tensorflow_version":
            tf.__version__,

        "platform":
            platform.platform(),

        "system":
            platform.system(),

        "machine":
            platform.machine(),

        "processor":
            platform.processor(),

        "hostname":
            socket.gethostname(),

        "gpu_devices":
            [
                str(
                    device
                )
                for device
                in gpu_devices
            ],

        "gpu_available":
            bool(
                gpu_devices
            ),

        "cuda_build":
            bool(
                tf.test.is_built_with_cuda()
            ),

        "working_directory":
            str(
                Path.cwd()
            ),

        "protocol_file":
            str(
                THIS_FILE
            ),

        "validated_baseline_protocol":
            str(
                BASELINE_PROTOCOL_PATH
            ),
    }


# ============================================================
# PARAMETER-BUDGET CHECK
# ============================================================

def parameter_budget_report(
    parameter_count: int,
    tolerance_fraction: float | None = None,
) -> Dict[str, Any]:

    parameter_count = int(
        parameter_count
    )


    if tolerance_fraction is None:

        tolerance_fraction = float(
            OPERATOR_CONFIG[
                "default_parameter_tolerance_fraction"
            ]
        )


    reference = int(
        OPERATOR_CONFIG[
            "reference_parameter_count"
        ]
    )


    absolute_difference = (
        parameter_count
        - reference
    )


    relative_difference = (
        absolute_difference
        / reference
    )


    within_budget = (
        abs(
            relative_difference
        )
        <= tolerance_fraction
    )


    return {

        "reference_parameter_count":
            reference,

        "observed_parameter_count":
            parameter_count,

        "absolute_difference":
            absolute_difference,

        "relative_difference":
            float(
                relative_difference
            ),

        "relative_difference_percent":
            float(
                relative_difference
                * 100.0
            ),

        "tolerance_fraction":
            float(
                tolerance_fraction
            ),

        "within_default_comparable_budget":
            bool(
                within_budget
            ),
    }


# ============================================================
# OPTIONAL STRICT PARAMETER CHECK
# ============================================================

def assert_comparable_parameter_budget(
    model,
    tolerance_fraction: float | None = None,
) -> Dict[str, Any]:

    parameter_count = (
        count_trainable_parameters(
            model
        )
    )


    report = (
        parameter_budget_report(
            parameter_count,
            tolerance_fraction=
                tolerance_fraction,
        )
    )


    if not report[
        "within_default_comparable_budget"
    ]:

        raise RuntimeError(
            "Model parameter budget is outside "
            "the permitted comparison range.\n"
            f"Reference parameters: "
            f"{report['reference_parameter_count']}\n"
            f"Observed parameters: "
            f"{report['observed_parameter_count']}\n"
            f"Difference: "
            f"{report['relative_difference_percent']:.3f}%\n"
            f"Tolerance: "
            f"{report['tolerance_fraction'] * 100:.1f}%"
        )


    return report


# ============================================================
# INITIALIZE MODERN-BASELINE EXPERIMENT
# ============================================================

def initialize_operator_experiment(
    model_name: str,
    model_specific_config: Dict[str, Any],
) -> Dict[str, Any]:

    set_determinism()


    all_files = (
        list_sequence_files()
    )


    (
        train_files,
        validation_files,
        test_files,
    ) = split_sequence_files(
        all_files
    )


    validate_split_integrity(
        train_files,
        validation_files,
        test_files,
    )


    model_slug = slugify(
        model_name
    )


    timestamp = datetime.now().strftime(
        "%Y%m%d-%H%M%S"
    )


    run_name = (
        f"{model_slug}_{timestamp}"
    )


    run_dir = (
        OUTPUT_ROOT
        / model_slug
        / run_name
    )


    models_dir = (
        run_dir
        / "models"
    )

    tables_dir = (
        run_dir
        / "tables"
    )

    figures_dir = (
        run_dir
        / "figures"
    )

    logs_dir = (
        run_dir
        / "logs"
    )


    for directory in [

        run_dir,
        models_dir,
        tables_dir,
        figures_dir,
        logs_dir,

    ]:

        directory.mkdir(
            parents=True,
            exist_ok=True,
        )


    # --------------------------------------------------------
    # SPLIT MANIFEST
    # --------------------------------------------------------

    split_manifest = {

        "total_sequences":
            len(
                all_files
            ),

        "train_count":
            len(
                train_files
            ),

        "validation_count":
            len(
                validation_files
            ),

        "test_count":
            len(
                test_files
            ),

        "train_fingerprint":
            split_fingerprint(
                train_files
            ),

        "validation_fingerprint":
            split_fingerprint(
                validation_files
            ),

        "test_fingerprint":
            split_fingerprint(
                test_files
            ),

        "train_files":
            [
                path.name
                for path
                in train_files
            ],

        "validation_files":
            [
                path.name
                for path
                in validation_files
            ],

        "test_files":
            [
                path.name
                for path
                in test_files
            ],
    }


    # --------------------------------------------------------
    # COMPLETE CONFIGURATION
    # --------------------------------------------------------

    complete_config = {

        "model_name":
            model_name,

        "run_name":
            run_name,

        "common_baseline_config":
            COMMON_CONFIG,

        "modern_baseline_protocol":
            OPERATOR_CONFIG,

        "model_specific_config":
            model_specific_config,

        "environment":
            environment_metadata(),

        "split_summary": {

            "total":
                len(
                    all_files
                ),

            "train":
                len(
                    train_files
                ),

            "validation":
                len(
                    validation_files
                ),

            "test":
                len(
                    test_files
                ),
        },
    }


    save_json(
        run_dir
        / "config.json",
        complete_config,
    )


    save_json(
        run_dir
        / "split_manifest.json",
        split_manifest,
    )


    split_rows = []


    for split_name, files in [

        (
            "train",
            train_files,
        ),

        (
            "validation",
            validation_files,
        ),

        (
            "test",
            test_files,
        ),

    ]:

        for index, path in enumerate(
            files
        ):

            split_rows.append(
                {
                    "split":
                        split_name,

                    "split_index":
                        index,

                    "filename":
                        path.name,

                    "path":
                        str(
                            path
                        ),
                }
            )


    save_csv(
        run_dir
        / "tables"
        / "split_manifest.csv",
        split_rows,
    )


    return {

        "run_dir":
            run_dir,

        "models_dir":
            models_dir,

        "tables_dir":
            tables_dir,

        "figures_dir":
            figures_dir,

        "logs_dir":
            logs_dir,

        "all_files":
            all_files,

        "train_files":
            train_files,

        "validation_files":
            validation_files,

        "test_files":
            test_files,

        "complete_config":
            complete_config,

        "split_manifest":
            split_manifest,
    }


# ============================================================
# RESULT RECORD
# ============================================================

def build_result_record(
    *,
    model_name: str,
    model,
    validation_metrics: Dict[str, Any],
    test_metrics: Dict[str, Any],
    latency_metrics: Dict[str, Any],
    training_time_sec: float,
    best_epoch: int,
    model_specific_config: Dict[str, Any],
    extra_results: Dict[str, Any] | None = None,
) -> Dict[str, Any]:

    parameter_count = (
        count_trainable_parameters(
            model
        )
    )


    budget_report = (
        parameter_budget_report(
            parameter_count
        )
    )


    result = {

        "experiment_family":
            OPERATOR_CONFIG[
                "experiment_family"
            ],

        "new_experiment":
            True,

        "replaces_existing_manuscript_numbers":
            False,

        "model_name":
            model_name,

        "parameter_count":
            parameter_count,

        "parameter_budget":
            budget_report,

        "best_epoch":
            int(
                best_epoch
            ),

        "training_time_sec":
            float(
                training_time_sec
            ),

        "validation_metrics":
            validation_metrics,

        "test_metrics":
            test_metrics,

        "latency_metrics":
            latency_metrics,

        "model_specific_config":
            model_specific_config,

        "common_protocol":
            COMMON_CONFIG,

        "modern_baseline_protocol":
            OPERATOR_CONFIG,

        "environment":
            environment_metadata(),

        "result_policy":
            (
                "Only experimentally generated values are "
                "contained in this result record. These results "
                "do not replace submitted-manuscript values."
            ),
    }


    if extra_results is not None:

        result[
            "extra_results"
        ] = extra_results


    return result


# ============================================================
# SELF-TEST
# ============================================================

def protocol_self_test() -> None:

    set_determinism()


    sequence_files = (
        list_sequence_files()
    )


    (
        train_files,
        validation_files,
        test_files,
    ) = split_sequence_files(
        sequence_files
    )


    validate_split_integrity(
        train_files,
        validation_files,
        test_files,
    )


    print()
    print("=" * 80)

    print(
        "COMMON MODERN-BASELINE / OPERATOR PROTOCOL SELF-TEST"
    )

    print("=" * 80)


    print(
        "Validated baseline protocol:"
    )

    print(
        BASELINE_PROTOCOL_PATH
    )


    print()


    print(
        "Project root:"
    )

    print(
        ORIGINAL_ROOT
    )


    print()


    print(
        "New branch:"
    )

    print(
        NEW_ROOT
    )


    print()


    print(
        "Sequence directory:"
    )

    print(
        SEQUENCE_DIR
    )


    print()


    print(
        "Sequences:"
    )

    print(
        f"  Total      : {len(sequence_files)}"
    )

    print(
        f"  Train      : {len(train_files)}"
    )

    print(
        f"  Validation : {len(validation_files)}"
    )

    print(
        f"  Test       : {len(test_files)}"
    )


    print()


    print(
        "Split fingerprints:"
    )

    print(
        "  Train      :",
        split_fingerprint(
            train_files
        )[:16],
    )

    print(
        "  Validation :",
        split_fingerprint(
            validation_files
        )[:16],
    )

    print(
        "  Test       :",
        split_fingerprint(
            test_files
        )[:16],
    )


    print()


    print(
        "Reference parameter budget:"
    )

    print(
        f"  {REFERENCE_PARAMETER_COUNT}"
    )


    print(
        "Default tolerance:"
    )

    print(
        f"  ±"
        f"{OPERATOR_CONFIG['default_parameter_tolerance_fraction'] * 100:.1f}%"
    )


    print()


    print(
        "Planned modern baselines:"
    )

    for model_name in OPERATOR_CONFIG[
        "planned_models"
    ]:

        print(
            f"  - {model_name}"
        )


    print()


    print(
        "Inherited common protocol:"
    )

    for key in [

        "seed",
        "train_fraction",
        "validation_fraction",
        "test_fraction",
        "input_channels",
        "output_channels",
        "input_semantics",
        "target_semantics",
        "batch_size",
        "epochs",
        "learning_rate",
        "optimizer",
        "physics_operator",
        "use_common_wave_residual",
        "metrics",
        "latency_warmup_runs",
        "latency_measurement_runs",
        "selection_metric",
        "test_policy",

    ]:

        print(
            f"  {key}: "
            f"{COMMON_CONFIG[key]}"
        )


    print()


    print(
        "Modern-baseline policy:"
    )

    print(
        "  experiment_family:",
        OPERATOR_CONFIG[
            "experiment_family"
        ],
    )

    print(
        "  new_experiment:",
        OPERATOR_CONFIG[
            "new_experiment"
        ],
    )

    print(
        "  replaces_existing_manuscript_numbers:",
        OPERATOR_CONFIG[
            "replaces_existing_manuscript_numbers"
        ],
    )


    print()


    print(
        "TensorFlow version:",
        tf.__version__,
    )


    print(
        "CUDA build:",
        tf.test.is_built_with_cuda(),
    )


    print(
        "GPU devices:",
        tf.config.list_physical_devices(
            "GPU"
        ),
    )


    print()


    print(
        "PASS: modern-baseline operator protocol is ready."
    )


# ============================================================
# ENTRY POINT
# ============================================================

if __name__ == "__main__":

    protocol_self_test()