name: inversephysics

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.12

  # Scientific Computing
  - numpy>=1.26
  - scipy>=1.13
  - pandas>=2.2

  # Machine Learning
  - tensorflow=2.19
  - keras>=3.11

  # Evaluation
  - scikit-learn>=1.7

  # Visualization
  - matplotlib>=3.10

  # Data Processing
  - h5py>=3.15

  # Utilities
  - tqdm>=4.67
  - joblib>=1.5
  - pyyaml>=6.0

  # Notebook Support
  - jupyter
  - ipykernel

  - pip

  - pip:
      - tensorflow-io-gcs-filesystem